version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "pip"
      directory: "/docs"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "pip"
      directory: "/tools/ci/scripts/cve"
      schedule:
          interval: "daily"
      versioning-strategy: increase
